### ISSUE TITLE
Checksums are missing

### ISSUE THREAD

**Issue by raincrash** [maudzung/human36m_preprocessing#1]
Hi,

Thanks for the contribution. While running the `download_all.py`, the checksums could not be processed as the `checksums.txt` file is missing. I think you'd need to grab that from `h36m-fetch`. If this is the issue, I can send a PR with the file.

**Comment by maudzung** [comment]
Thanks for your comment.
Please send me a PR for the issue.

**Comment by raincrash** [comment]
Done https://github.com/maudzung/human36m_preprocessing/pull/2
