### ISSUE TITLE
mat files not exists

### ISSUE THREAD

**Issue by guker** [maudzung/human36m_preprocessing#3]
https://github.com/maudzung/human36m_preprocessing/blob/b52af52c1455b176f694bd46c79be65e98552adc/protocol_1.py#L146

i can not find mat file

**Comment by maudzung** [comment]
@guker Did you execute _python extract_all.py_? The *.tgz* files need to be extracted after you download the dataset.

**Comment by maudzung** [comment]
This is not an issue.
